# Autogenerated by LiteX / git: c0517cd1
import os
import sys
import pprint

home = "/home/carlos/Embedded/efinity/2023.2"

os.environ["EFXPT_HOME"]  = home + "/pt"
os.environ["EFXPGM_HOME"] = home + "/pgm"
os.environ["EFXDBG_HOME"] = home + "/debugger"
os.environ["EFXIPM_HOME"] = home + "/ipm"

sys.path.append(home + "/pt/bin")
sys.path.append(home + "/lib/python3.8/site-packages")

from api_service.design import DesignAPI
from api_service.device import DeviceAPI

is_verbose = True

design = DesignAPI(is_verbose)
device = DeviceAPI(is_verbose)

design.create("SOC", "T20Q144", ".", overwrite=True)


design.create_input_gpio("clk")
design.create_input_gpio("resetn")
design.create_output_gpio("TXD")
design.create_input_gpio("RXD")
design.create_output_gpio("LEDS")
design.assign_pkg_pin("clk","75")
design.set_property(  "clk","IO_STANDARD","3.3_V_LVTTL_/_LVCMOS")

design.assign_pkg_pin("resetn","74")
design.set_property(  "resetn","IO_STANDARD","3.3_V_LVTTL_/_LVCMOS")
design.set_property(  "resetn","PULL_OPTION","WEAK_PULLUP")

design.assign_pkg_pin("TXD","142")
design.set_property(  "TXD","IO_STANDARD","3.3_V_LVTTL_/_LVCMOS")
design.set_property(  "TXD","PULL_OPTION","WEAK_PULLUP")

design.assign_pkg_pin("RXD","144")
design.set_property(  "RXD","IO_STANDARD","3.3_V_LVTTL_/_LVCMOS")
design.set_property(  "RXD","PULL_OPTION","WEAK_PULLUP")

design.assign_pkg_pin("LEDS","20")
design.set_property(  "LEDS","IO_STANDARD","3.3_V_LVTTL_/_LVCMOS")
design.set_property(  "LEDS","DRIVE_STRENGTH","3")

# Check design, generate constraints and reports
design.generate(enable_bitstream=True)
# Save the configured periphery design
design.save()