/* Generated by Yosys 0.9+4288 (git sha1 b2e97174, x86_64-conda_cos6-linux-gnu-gcc 1.24.0.133_b0863d8_dirty -fvisibility-inlines-hidden -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -fdebug-prefix-map=/home/runner/work/conda-eda/conda-eda/workdir/conda-env/conda-bld/yosys_1630451134687/work=/usr/local/src/conda/yosys-0.9_5586_gb2e97174 -fdebug-prefix-map=/home/carlos/miniconda3/envs/fpga=/usr/local/src/conda-prefix -fPIC -Os -fno-merge-constants) */

/* top =  1  */
/* src = "MappedSPIFlash_V3.v:3.1-143.10" */
module MappedSPIFlash(clk, reset, rstrb, word_address, rdata, rbusy, CLK, CS_N, MOSI, MISO);
  /* src = "MappedSPIFlash_V3.v:13.23-13.26" */
  output CLK;
  /* src = "MappedSPIFlash_V3.v:53.25-53.37" */
  wire CLK_SB_DFFNESR_Q_D;
  wire CLK_SB_DFFNESR_Q_E;
  /* force_downto = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" */
  wire [3:0] CLK_SB_DFFNESR_Q_E_SB_LUT4_O_I1;
  wire CLK_SB_DFFNESR_Q_R;
  /* src = "MappedSPIFlash_V3.v:14.24-14.28" */
  output CS_N;
  wire CS_N_SB_DFFNE_Q_D;
  wire CS_N_SB_DFFNE_Q_E;
  /* src = "MappedSPIFlash_V3.v:16.24-16.28" */
  input MISO;
  /* src = "MappedSPIFlash_V3.v:15.24-15.28" */
  output MOSI;
  wire MOSI_SB_DFFNESR_Q_R;
  /* src = "MappedSPIFlash_V3.v:4.24-4.27" */
  input clk;
  /* src = "MappedSPIFlash_V3.v:31.6-31.13" */
  wire clk_div;
  wire clk_div_SB_DFFNSR_Q_D;
  /* force_downto = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:50.11-50.33|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:37.23-37.25" */
  wire [5:0] clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3;
  /* force_downto = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:50.11-50.33|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:51.21-51.22" */
  wire [5:0] clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI;
  /* force_downto = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" */
  wire [2:0] clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_LUT4_I3_O;
  /* force_downto = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" */
  wire [2:0] clk_div_SB_LUT4_I0_O;
  /* force_downto = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" */
  wire [2:0] clk_div_SB_LUT4_I2_O;
  /* force_downto = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" */
  wire [3:0] clk_div_SB_LUT4_I3_1_O;
  /* force_downto = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" */
  wire [3:0] clk_div_SB_LUT4_I3_I0;
  /* force_downto = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" */
  wire [3:0] clk_div_SB_LUT4_I3_O;
  /* src = "MappedSPIFlash_V3.v:36.15-36.23" */
  wire [31:0] cmd_addr;
  wire cmd_addr_SB_DFFNE_Q_10_D;
  wire cmd_addr_SB_DFFNE_Q_11_D;
  wire cmd_addr_SB_DFFNE_Q_12_D;
  wire cmd_addr_SB_DFFNE_Q_13_D;
  wire cmd_addr_SB_DFFNE_Q_14_D;
  wire cmd_addr_SB_DFFNE_Q_15_D;
  wire cmd_addr_SB_DFFNE_Q_16_D;
  wire cmd_addr_SB_DFFNE_Q_17_D;
  wire cmd_addr_SB_DFFNE_Q_18_D;
  wire cmd_addr_SB_DFFNE_Q_19_D;
  wire cmd_addr_SB_DFFNE_Q_1_D;
  wire cmd_addr_SB_DFFNE_Q_2_D;
  wire cmd_addr_SB_DFFNE_Q_3_D;
  wire cmd_addr_SB_DFFNE_Q_4_D;
  wire cmd_addr_SB_DFFNE_Q_5_D;
  wire cmd_addr_SB_DFFNE_Q_6_D;
  wire cmd_addr_SB_DFFNE_Q_7_D;
  wire cmd_addr_SB_DFFNE_Q_8_D;
  wire cmd_addr_SB_DFFNE_Q_9_D;
  wire cmd_addr_SB_DFFNE_Q_D;
  /* src = "MappedSPIFlash_V3.v:40.15-40.26" */
  wire [5:0] div_counter;
  /* force_downto = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:50.11-50.33|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:49.21-49.23" */
  wire [5:0] div_counter_SB_DFFNSR_Q_5_D;
  /* force_downto = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:57.26-57.41|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:33.26-33.27" */
  wire [5:0] div_counter_SB_DFFNSR_Q_D;
  /* force_downto = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:57.26-57.41|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:51.21-51.22" */
  wire [5:0] div_counter_SB_DFFNSR_Q_D_SB_LUT4_O_I3;
  /* src = "MappedSPIFlash_V3.v:10.23-10.28" */
  output rbusy;
  /* src = "MappedSPIFlash_V3.v:37.15-37.27" */
  wire [5:0] rcv_bitcount;
  /* force_downto = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:0.0-0.0|MappedSPIFlash_V3.v:71.5-127.12|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/techmap.v:578.19-578.22" */
  wire [5:0] rcv_bitcount_SB_DFFNESR_Q_5_D;
  /* force_downto = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:117.31-117.50|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:51.21-51.22" */
  wire [5:0] rcv_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3;
  /* force_downto = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:0.0-0.0|MappedSPIFlash_V3.v:71.5-127.12|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/techmap.v:583.28-583.35" */
  /* unused_bits = "5" */
  wire [11:0] rcv_bitcount_SB_DFFNESR_Q_D;
  wire rcv_bitcount_SB_DFFNESR_Q_E;
  /* src = "MappedSPIFlash_V3.v:38.15-38.23" */
  wire [31:0] rcv_data;
  /* src = "MappedSPIFlash_V3.v:9.24-9.29" */
  output [31:0] rdata;
  /* src = "MappedSPIFlash_V3.v:5.24-5.29" */
  input reset;
  /* force_downto = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" */
  wire [3:0] reset_SB_LUT4_I3_O;
  /* src = "MappedSPIFlash_V3.v:6.24-6.29" */
  input rstrb;
  /* force_downto = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" */
  wire [2:0] rstrb_SB_LUT4_I2_O;
  wire rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O;
  wire rstrb_SB_LUT4_I2_O_SB_LUT4_I3_O;
  /* src = "MappedSPIFlash_V3.v:35.15-35.27" */
  wire [5:0] snd_bitcount;
  /* force_downto = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:0.0-0.0|MappedSPIFlash_V3.v:71.5-127.12|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/techmap.v:578.19-578.22" */
  wire [5:0] snd_bitcount_SB_DFFNESR_Q_5_D;
  /* force_downto = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:102.29-102.48|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:51.21-51.22" */
  wire [5:0] snd_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3;
  /* force_downto = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:0.0-0.0|MappedSPIFlash_V3.v:71.5-127.12|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/techmap.v:583.28-583.35" */
  /* unused_bits = "5" */
  wire [11:0] snd_bitcount_SB_DFFNESR_Q_D;
  /* force_downto = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:6.21-6.22" */
  wire [3:0] snd_bitcount_SB_DFFNESR_Q_R;
  /* onehot = 32'd1 */
  wire [3:0] state;
  wire state_SB_DFFN_Q_1_D;
  wire state_SB_DFFN_Q_2_D;
  wire state_SB_DFFN_Q_D;
  /* src = "MappedSPIFlash_V3.v:7.24-7.36" */
  input [19:0] word_address;
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:43.1-64.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR CLK_SB_DFFNESR_Q (
    .C(clk),
    .D(CLK_SB_DFFNESR_Q_D),
    .E(CLK_SB_DFFNESR_Q_E),
    .Q(CLK),
    .R(CLK_SB_DFFNESR_Q_R)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hffc0)
  ) CLK_SB_DFFNESR_Q_E_SB_LUT4_O (
    .I0(1'h0),
    .I1(CLK_SB_DFFNESR_Q_E_SB_LUT4_O_I1[1]),
    .I2(clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_LUT4_I3_O[1]),
    .I3(clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_LUT4_I3_O[2]),
    .O(CLK_SB_DFFNESR_Q_E)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h1000)
  ) CLK_SB_DFFNESR_Q_E_SB_LUT4_O_I1_SB_LUT4_O (
    .I0(div_counter[3]),
    .I1(div_counter[0]),
    .I2(div_counter[1]),
    .I3(div_counter[2]),
    .O(CLK_SB_DFFNESR_Q_E_SB_LUT4_O_I1[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h000f)
  ) CLK_SB_DFFNESR_Q_E_SB_LUT4_O_I1_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(div_counter[4]),
    .I3(div_counter[5]),
    .O(CLK_SB_DFFNESR_Q_E_SB_LUT4_O_I1[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) CLK_SB_DFFNESR_Q_R_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(reset),
    .O(CLK_SB_DFFNESR_Q_R)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h000f)
  ) CLK_SB_LUT4_I3 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(CS_N),
    .I3(CLK),
    .O(CLK_SB_DFFNESR_Q_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE CS_N_SB_DFFNE_Q (
    .C(clk),
    .D(CS_N_SB_DFFNE_Q_D),
    .E(CS_N_SB_DFFNE_Q_E),
    .Q(CS_N)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) CS_N_SB_DFFNE_Q_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(state[2]),
    .O(CS_N_SB_DFFNE_Q_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hfc00)
  ) CS_N_SB_DFFNE_Q_E_SB_LUT4_O (
    .I0(1'h0),
    .I1(state[0]),
    .I2(state[2]),
    .I3(rstrb_SB_LUT4_I2_O[2]),
    .O(CS_N_SB_DFFNE_Q_E)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR MOSI_SB_DFFNESR_Q (
    .C(clk),
    .D(cmd_addr[30]),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(MOSI),
    .R(MOSI_SB_DFFNESR_Q_R)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) MOSI_SB_DFFNESR_Q_R_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(state[1]),
    .O(MOSI_SB_DFFNESR_Q_R)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:43.1-64.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:17.59-17.105" */
  SB_DFFNSR clk_div_SB_DFFNSR_Q (
    .C(clk),
    .D(clk_div_SB_DFFNSR_Q_D),
    .Q(clk_div),
    .R(CLK_SB_DFFNESR_Q_R)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hc0ff)
  ) clk_div_SB_DFFNSR_Q_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(CLK_SB_DFFNESR_Q_E_SB_LUT4_O_I1[0]),
    .I2(CLK_SB_DFFNESR_Q_E_SB_LUT4_O_I1[1]),
    .I3(clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3[5]),
    .O(clk_div_SB_DFFNSR_Q_D)
  );
  /* src = "MappedSPIFlash_V3.v:50.11-50.33|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO (
    .CI(clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI[5]),
    .CO(clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3[5]),
    .I0(1'h0),
    .I1(div_counter_SB_DFFNSR_Q_5_D[5])
  );
  /* src = "MappedSPIFlash_V3.v:50.11-50.33|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI_SB_CARRY_CO (
    .CI(clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI[4]),
    .CO(clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI[5]),
    .I0(1'h0),
    .I1(div_counter_SB_DFFNSR_Q_5_D[4])
  );
  /* src = "MappedSPIFlash_V3.v:50.11-50.33|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI_SB_CARRY_CO_1 (
    .CI(clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI[3]),
    .CO(clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI[4]),
    .I0(1'h0),
    .I1(div_counter_SB_DFFNSR_Q_5_D[3])
  );
  /* src = "MappedSPIFlash_V3.v:50.11-50.33|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI_SB_CARRY_CO_2 (
    .CI(clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI[2]),
    .CO(clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI[3]),
    .I0(1'h1),
    .I1(div_counter_SB_DFFNSR_Q_5_D[2])
  );
  /* src = "MappedSPIFlash_V3.v:50.11-50.33|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI_SB_CARRY_CO_3 (
    .CI(div_counter_SB_DFFNSR_Q_5_D[0]),
    .CO(clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI[2]),
    .I0(1'h1),
    .I1(div_counter_SB_DFFNSR_Q_5_D[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h8fff)
  ) clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_LUT4_I3 (
    .I0(CLK_SB_DFFNESR_Q_E_SB_LUT4_O_I1[0]),
    .I1(CLK_SB_DFFNESR_Q_E_SB_LUT4_O_I1[1]),
    .I2(reset),
    .I3(clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3[5]),
    .O(clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_LUT4_I3_O[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h1000)
  ) clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_LUT4_I3_O_SB_LUT4_O (
    .I0(div_counter[2]),
    .I1(div_counter[3]),
    .I2(div_counter[1]),
    .I3(div_counter[0]),
    .O(clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_LUT4_I3_O[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h7f00)
  ) clk_div_SB_LUT4_I0 (
    .I0(clk_div),
    .I1(clk_div_SB_LUT4_I3_I0[1]),
    .I2(clk_div_SB_LUT4_I3_I0[0]),
    .I3(state[1]),
    .O(clk_div_SB_LUT4_I0_O[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h0300)
  ) clk_div_SB_LUT4_I0_O_SB_LUT4_I1 (
    .I0(1'h0),
    .I1(clk_div_SB_LUT4_I0_O[0]),
    .I2(clk_div_SB_LUT4_I0_O[1]),
    .I3(clk_div_SB_LUT4_I0_O[2]),
    .O(rcv_bitcount_SB_DFFNESR_Q_E)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h00cf)
  ) clk_div_SB_LUT4_I0_O_SB_LUT4_O (
    .I0(1'h0),
    .I1(state[0]),
    .I2(clk_div_SB_LUT4_I2_O[1]),
    .I3(clk_div_SB_LUT4_I2_O[2]),
    .O(clk_div_SB_LUT4_I0_O[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h80ff)
  ) clk_div_SB_LUT4_I0_O_SB_LUT4_O_1 (
    .I0(clk_div_SB_LUT4_I3_1_O[0]),
    .I1(clk_div_SB_LUT4_I3_1_O[1]),
    .I2(clk_div_SB_LUT4_I3_1_O[2]),
    .I3(reset),
    .O(clk_div_SB_LUT4_I0_O[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h0f00)
  ) clk_div_SB_LUT4_I2 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(clk_div),
    .I3(state[3]),
    .O(clk_div_SB_LUT4_I2_O[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h0f00)
  ) clk_div_SB_LUT4_I2_1 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(clk_div),
    .I3(state[1]),
    .O(clk_div_SB_LUT4_I3_O[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h000f)
  ) clk_div_SB_LUT4_I2_O_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(state[1]),
    .I3(state[3]),
    .O(clk_div_SB_LUT4_I2_O[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h8000)
  ) clk_div_SB_LUT4_I3 (
    .I0(clk_div_SB_LUT4_I3_I0[0]),
    .I1(clk_div_SB_LUT4_I3_I0[1]),
    .I2(state[1]),
    .I3(clk_div),
    .O(clk_div_SB_LUT4_I3_O[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf000)
  ) clk_div_SB_LUT4_I3_1 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(state[3]),
    .I3(clk_div),
    .O(clk_div_SB_LUT4_I3_1_O[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h0100)
  ) clk_div_SB_LUT4_I3_1_O_SB_LUT4_O (
    .I0(rcv_bitcount[3]),
    .I1(rcv_bitcount[4]),
    .I2(rcv_bitcount[5]),
    .I3(rcv_bitcount[0]),
    .O(clk_div_SB_LUT4_I3_1_O[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h000f)
  ) clk_div_SB_LUT4_I3_1_O_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(rcv_bitcount[1]),
    .I3(rcv_bitcount[2]),
    .O(clk_div_SB_LUT4_I3_1_O[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h0100)
  ) clk_div_SB_LUT4_I3_I0_SB_LUT4_O (
    .I0(snd_bitcount[3]),
    .I1(snd_bitcount[4]),
    .I2(snd_bitcount[5]),
    .I3(snd_bitcount[0]),
    .O(clk_div_SB_LUT4_I3_I0[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h000f)
  ) clk_div_SB_LUT4_I3_I0_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(snd_bitcount[1]),
    .I3(snd_bitcount[2]),
    .O(clk_div_SB_LUT4_I3_I0[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h0003)
  ) clk_div_SB_LUT4_I3_O_SB_LUT4_O (
    .I0(1'h0),
    .I1(state[1]),
    .I2(state[2]),
    .I3(state[0]),
    .O(clk_div_SB_LUT4_I3_O[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR cmd_addr_SB_DFFNESR_Q (
    .C(clk),
    .D(cmd_addr[29]),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[30]),
    .R(MOSI_SB_DFFNESR_Q_R)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR cmd_addr_SB_DFFNESR_Q_1 (
    .C(clk),
    .D(cmd_addr[28]),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[29]),
    .R(MOSI_SB_DFFNESR_Q_R)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR cmd_addr_SB_DFFNESR_Q_2 (
    .C(clk),
    .D(cmd_addr[27]),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[28]),
    .R(MOSI_SB_DFFNESR_Q_R)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR cmd_addr_SB_DFFNESR_Q_3 (
    .C(clk),
    .D(cmd_addr[26]),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[27]),
    .R(MOSI_SB_DFFNESR_Q_R)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR cmd_addr_SB_DFFNESR_Q_4 (
    .C(clk),
    .D(cmd_addr[25]),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[26]),
    .R(MOSI_SB_DFFNESR_Q_R)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR cmd_addr_SB_DFFNESR_Q_5 (
    .C(clk),
    .D(cmd_addr[22]),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[23]),
    .R(MOSI_SB_DFFNESR_Q_R)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR cmd_addr_SB_DFFNESR_Q_6 (
    .C(clk),
    .D(cmd_addr[21]),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[22]),
    .R(MOSI_SB_DFFNESR_Q_R)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR cmd_addr_SB_DFFNESR_Q_7 (
    .C(clk),
    .D(cmd_addr[0]),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[1]),
    .R(MOSI_SB_DFFNESR_Q_R)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:23.66-23.119" */
  SB_DFFNESS cmd_addr_SB_DFFNESS_Q (
    .C(clk),
    .D(cmd_addr[24]),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[25]),
    .S(MOSI_SB_DFFNESR_Q_R)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:23.66-23.119" */
  SB_DFFNESS cmd_addr_SB_DFFNESS_Q_1 (
    .C(clk),
    .D(cmd_addr[23]),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[24]),
    .S(MOSI_SB_DFFNESR_Q_R)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE cmd_addr_SB_DFFNE_Q (
    .C(clk),
    .D(cmd_addr_SB_DFFNE_Q_D),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[21])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE cmd_addr_SB_DFFNE_Q_1 (
    .C(clk),
    .D(cmd_addr_SB_DFFNE_Q_1_D),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[20])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE cmd_addr_SB_DFFNE_Q_10 (
    .C(clk),
    .D(cmd_addr_SB_DFFNE_Q_10_D),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) cmd_addr_SB_DFFNE_Q_10_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(word_address[9]),
    .I2(cmd_addr[10]),
    .I3(state[1]),
    .O(cmd_addr_SB_DFFNE_Q_10_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE cmd_addr_SB_DFFNE_Q_11 (
    .C(clk),
    .D(cmd_addr_SB_DFFNE_Q_11_D),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) cmd_addr_SB_DFFNE_Q_11_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(word_address[8]),
    .I2(cmd_addr[9]),
    .I3(state[1]),
    .O(cmd_addr_SB_DFFNE_Q_11_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE cmd_addr_SB_DFFNE_Q_12 (
    .C(clk),
    .D(cmd_addr_SB_DFFNE_Q_12_D),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) cmd_addr_SB_DFFNE_Q_12_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(word_address[7]),
    .I2(cmd_addr[8]),
    .I3(state[1]),
    .O(cmd_addr_SB_DFFNE_Q_12_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE cmd_addr_SB_DFFNE_Q_13 (
    .C(clk),
    .D(cmd_addr_SB_DFFNE_Q_13_D),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) cmd_addr_SB_DFFNE_Q_13_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(word_address[6]),
    .I2(cmd_addr[7]),
    .I3(state[1]),
    .O(cmd_addr_SB_DFFNE_Q_13_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE cmd_addr_SB_DFFNE_Q_14 (
    .C(clk),
    .D(cmd_addr_SB_DFFNE_Q_14_D),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) cmd_addr_SB_DFFNE_Q_14_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(word_address[5]),
    .I2(cmd_addr[6]),
    .I3(state[1]),
    .O(cmd_addr_SB_DFFNE_Q_14_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE cmd_addr_SB_DFFNE_Q_15 (
    .C(clk),
    .D(cmd_addr_SB_DFFNE_Q_15_D),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) cmd_addr_SB_DFFNE_Q_15_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(word_address[4]),
    .I2(cmd_addr[5]),
    .I3(state[1]),
    .O(cmd_addr_SB_DFFNE_Q_15_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE cmd_addr_SB_DFFNE_Q_16 (
    .C(clk),
    .D(cmd_addr_SB_DFFNE_Q_16_D),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) cmd_addr_SB_DFFNE_Q_16_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(word_address[3]),
    .I2(cmd_addr[4]),
    .I3(state[1]),
    .O(cmd_addr_SB_DFFNE_Q_16_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE cmd_addr_SB_DFFNE_Q_17 (
    .C(clk),
    .D(cmd_addr_SB_DFFNE_Q_17_D),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) cmd_addr_SB_DFFNE_Q_17_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(word_address[2]),
    .I2(cmd_addr[3]),
    .I3(state[1]),
    .O(cmd_addr_SB_DFFNE_Q_17_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE cmd_addr_SB_DFFNE_Q_18 (
    .C(clk),
    .D(cmd_addr_SB_DFFNE_Q_18_D),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) cmd_addr_SB_DFFNE_Q_18_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(word_address[1]),
    .I2(cmd_addr[2]),
    .I3(state[1]),
    .O(cmd_addr_SB_DFFNE_Q_18_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE cmd_addr_SB_DFFNE_Q_19 (
    .C(clk),
    .D(cmd_addr_SB_DFFNE_Q_19_D),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) cmd_addr_SB_DFFNE_Q_19_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(word_address[0]),
    .I2(cmd_addr[1]),
    .I3(state[1]),
    .O(cmd_addr_SB_DFFNE_Q_19_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) cmd_addr_SB_DFFNE_Q_1_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(word_address[18]),
    .I2(cmd_addr[19]),
    .I3(state[1]),
    .O(cmd_addr_SB_DFFNE_Q_1_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE cmd_addr_SB_DFFNE_Q_2 (
    .C(clk),
    .D(cmd_addr_SB_DFFNE_Q_2_D),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[19])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE cmd_addr_SB_DFFNE_Q_20 (
    .C(clk),
    .D(state[1]),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) cmd_addr_SB_DFFNE_Q_2_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(word_address[17]),
    .I2(cmd_addr[18]),
    .I3(state[1]),
    .O(cmd_addr_SB_DFFNE_Q_2_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE cmd_addr_SB_DFFNE_Q_3 (
    .C(clk),
    .D(cmd_addr_SB_DFFNE_Q_3_D),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[18])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) cmd_addr_SB_DFFNE_Q_3_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(word_address[16]),
    .I2(cmd_addr[17]),
    .I3(state[1]),
    .O(cmd_addr_SB_DFFNE_Q_3_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE cmd_addr_SB_DFFNE_Q_4 (
    .C(clk),
    .D(cmd_addr_SB_DFFNE_Q_4_D),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[17])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) cmd_addr_SB_DFFNE_Q_4_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(word_address[15]),
    .I2(cmd_addr[16]),
    .I3(state[1]),
    .O(cmd_addr_SB_DFFNE_Q_4_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE cmd_addr_SB_DFFNE_Q_5 (
    .C(clk),
    .D(cmd_addr_SB_DFFNE_Q_5_D),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[16])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) cmd_addr_SB_DFFNE_Q_5_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(word_address[14]),
    .I2(cmd_addr[15]),
    .I3(state[1]),
    .O(cmd_addr_SB_DFFNE_Q_5_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE cmd_addr_SB_DFFNE_Q_6 (
    .C(clk),
    .D(cmd_addr_SB_DFFNE_Q_6_D),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) cmd_addr_SB_DFFNE_Q_6_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(word_address[13]),
    .I2(cmd_addr[14]),
    .I3(state[1]),
    .O(cmd_addr_SB_DFFNE_Q_6_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE cmd_addr_SB_DFFNE_Q_7 (
    .C(clk),
    .D(cmd_addr_SB_DFFNE_Q_7_D),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) cmd_addr_SB_DFFNE_Q_7_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(word_address[12]),
    .I2(cmd_addr[13]),
    .I3(state[1]),
    .O(cmd_addr_SB_DFFNE_Q_7_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE cmd_addr_SB_DFFNE_Q_8 (
    .C(clk),
    .D(cmd_addr_SB_DFFNE_Q_8_D),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) cmd_addr_SB_DFFNE_Q_8_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(word_address[11]),
    .I2(cmd_addr[12]),
    .I3(state[1]),
    .O(cmd_addr_SB_DFFNE_Q_8_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE cmd_addr_SB_DFFNE_Q_9 (
    .C(clk),
    .D(cmd_addr_SB_DFFNE_Q_9_D),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O),
    .Q(cmd_addr[12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) cmd_addr_SB_DFFNE_Q_9_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(word_address[10]),
    .I2(cmd_addr[11]),
    .I3(state[1]),
    .O(cmd_addr_SB_DFFNE_Q_9_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf0cc)
  ) cmd_addr_SB_DFFNE_Q_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(word_address[19]),
    .I2(cmd_addr[20]),
    .I3(state[1]),
    .O(cmd_addr_SB_DFFNE_Q_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:43.1-64.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:17.59-17.105" */
  SB_DFFNSR div_counter_SB_DFFNSR_Q (
    .C(clk),
    .D(div_counter_SB_DFFNSR_Q_D[5]),
    .Q(div_counter[5]),
    .R(clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_LUT4_I3_O[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:43.1-64.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:17.59-17.105" */
  SB_DFFNSR div_counter_SB_DFFNSR_Q_1 (
    .C(clk),
    .D(div_counter_SB_DFFNSR_Q_D[4]),
    .Q(div_counter[4]),
    .R(clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_LUT4_I3_O[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:43.1-64.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:17.59-17.105" */
  SB_DFFNSR div_counter_SB_DFFNSR_Q_2 (
    .C(clk),
    .D(div_counter_SB_DFFNSR_Q_D[3]),
    .Q(div_counter[3]),
    .R(clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_LUT4_I3_O[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:43.1-64.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:17.59-17.105" */
  SB_DFFNSR div_counter_SB_DFFNSR_Q_3 (
    .C(clk),
    .D(div_counter_SB_DFFNSR_Q_D[2]),
    .Q(div_counter[2]),
    .R(clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_LUT4_I3_O[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:43.1-64.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:17.59-17.105" */
  SB_DFFNSR div_counter_SB_DFFNSR_Q_4 (
    .C(clk),
    .D(div_counter_SB_DFFNSR_Q_D[1]),
    .Q(div_counter[1]),
    .R(clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_LUT4_I3_O[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:43.1-64.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:17.59-17.105" */
  SB_DFFNSR div_counter_SB_DFFNSR_Q_5 (
    .C(clk),
    .D(div_counter_SB_DFFNSR_Q_5_D[0]),
    .Q(div_counter[0]),
    .R(clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_LUT4_I3_O[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) div_counter_SB_DFFNSR_Q_5_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(div_counter[2]),
    .O(div_counter_SB_DFFNSR_Q_5_D[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) div_counter_SB_DFFNSR_Q_5_D_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(div_counter[1]),
    .O(div_counter_SB_DFFNSR_Q_5_D[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) div_counter_SB_DFFNSR_Q_5_D_SB_LUT4_O_2 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(div_counter[5]),
    .O(div_counter_SB_DFFNSR_Q_5_D[5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) div_counter_SB_DFFNSR_Q_5_D_SB_LUT4_O_3 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(div_counter[4]),
    .O(div_counter_SB_DFFNSR_Q_5_D[4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) div_counter_SB_DFFNSR_Q_5_D_SB_LUT4_O_4 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(div_counter[3]),
    .O(div_counter_SB_DFFNSR_Q_5_D[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:12.34-13.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h00ff)
  ) div_counter_SB_DFFNSR_Q_5_D_SB_LUT4_O_5 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(1'h0),
    .I3(div_counter[0]),
    .O(div_counter_SB_DFFNSR_Q_5_D[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:57.26-57.41|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) div_counter_SB_DFFNSR_Q_D_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(div_counter[5]),
    .I3(div_counter_SB_DFFNSR_Q_D_SB_LUT4_O_I3[5]),
    .O(div_counter_SB_DFFNSR_Q_D[5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:57.26-57.41|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) div_counter_SB_DFFNSR_Q_D_SB_LUT4_O_1 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(div_counter[4]),
    .I3(div_counter_SB_DFFNSR_Q_D_SB_LUT4_O_I3[4]),
    .O(div_counter_SB_DFFNSR_Q_D[4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:57.26-57.41|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) div_counter_SB_DFFNSR_Q_D_SB_LUT4_O_2 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(div_counter[3]),
    .I3(div_counter_SB_DFFNSR_Q_D_SB_LUT4_O_I3[3]),
    .O(div_counter_SB_DFFNSR_Q_D[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:57.26-57.41|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) div_counter_SB_DFFNSR_Q_D_SB_LUT4_O_3 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(div_counter[2]),
    .I3(div_counter_SB_DFFNSR_Q_D_SB_LUT4_O_I3[2]),
    .O(div_counter_SB_DFFNSR_Q_D[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:57.26-57.41|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h6996)
  ) div_counter_SB_DFFNSR_Q_D_SB_LUT4_O_4 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(div_counter[1]),
    .I3(div_counter[0]),
    .O(div_counter_SB_DFFNSR_Q_D[1])
  );
  /* src = "MappedSPIFlash_V3.v:57.26-57.41|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY div_counter_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO (
    .CI(div_counter_SB_DFFNSR_Q_D_SB_LUT4_O_I3[4]),
    .CO(div_counter_SB_DFFNSR_Q_D_SB_LUT4_O_I3[5]),
    .I0(1'h0),
    .I1(div_counter[4])
  );
  /* src = "MappedSPIFlash_V3.v:57.26-57.41|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY div_counter_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_1 (
    .CI(div_counter_SB_DFFNSR_Q_D_SB_LUT4_O_I3[3]),
    .CO(div_counter_SB_DFFNSR_Q_D_SB_LUT4_O_I3[4]),
    .I0(1'h0),
    .I1(div_counter[3])
  );
  /* src = "MappedSPIFlash_V3.v:57.26-57.41|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY div_counter_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_2 (
    .CI(div_counter_SB_DFFNSR_Q_D_SB_LUT4_O_I3[2]),
    .CO(div_counter_SB_DFFNSR_Q_D_SB_LUT4_O_I3[3]),
    .I0(1'h0),
    .I1(div_counter[2])
  );
  /* src = "MappedSPIFlash_V3.v:57.26-57.41|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY div_counter_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_3 (
    .CI(div_counter[0]),
    .CO(div_counter_SB_DFFNSR_Q_D_SB_LUT4_O_I3[2]),
    .I0(1'h0),
    .I1(div_counter[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR rcv_bitcount_SB_DFFNESR_Q (
    .C(clk),
    .D(rcv_bitcount_SB_DFFNESR_Q_D[0]),
    .E(rcv_bitcount_SB_DFFNESR_Q_E),
    .Q(rcv_bitcount[0]),
    .R(clk_div_SB_LUT4_I2_O[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR rcv_bitcount_SB_DFFNESR_Q_1 (
    .C(clk),
    .D(rcv_bitcount_SB_DFFNESR_Q_D[1]),
    .E(rcv_bitcount_SB_DFFNESR_Q_E),
    .Q(rcv_bitcount[1]),
    .R(clk_div_SB_LUT4_I2_O[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR rcv_bitcount_SB_DFFNESR_Q_2 (
    .C(clk),
    .D(rcv_bitcount_SB_DFFNESR_Q_D[2]),
    .E(rcv_bitcount_SB_DFFNESR_Q_E),
    .Q(rcv_bitcount[2]),
    .R(clk_div_SB_LUT4_I2_O[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR rcv_bitcount_SB_DFFNESR_Q_3 (
    .C(clk),
    .D(rcv_bitcount_SB_DFFNESR_Q_D[3]),
    .E(rcv_bitcount_SB_DFFNESR_Q_E),
    .Q(rcv_bitcount[3]),
    .R(clk_div_SB_LUT4_I2_O[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR rcv_bitcount_SB_DFFNESR_Q_4 (
    .C(clk),
    .D(rcv_bitcount_SB_DFFNESR_Q_D[4]),
    .E(rcv_bitcount_SB_DFFNESR_Q_E),
    .Q(rcv_bitcount[4]),
    .R(clk_div_SB_LUT4_I2_O[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR rcv_bitcount_SB_DFFNESR_Q_5 (
    .C(clk),
    .D(rcv_bitcount_SB_DFFNESR_Q_5_D[5]),
    .E(rcv_bitcount_SB_DFFNESR_Q_E),
    .Q(rcv_bitcount[5]),
    .R(clk_div_SB_LUT4_I2_O[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:117.31-117.50|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf8f2)
  ) rcv_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O (
    .I0(state[3]),
    .I1(rcv_bitcount[5]),
    .I2(state[1]),
    .I3(rcv_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[5]),
    .O(rcv_bitcount_SB_DFFNESR_Q_5_D[5])
  );
  /* src = "MappedSPIFlash_V3.v:117.31-117.50|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY rcv_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3_SB_CARRY_CO (
    .CI(rcv_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[4]),
    .CO(rcv_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[5]),
    .I0(rcv_bitcount[4]),
    .I1(1'h1)
  );
  /* src = "MappedSPIFlash_V3.v:117.31-117.50|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY rcv_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3_SB_CARRY_CO_1 (
    .CI(rcv_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[3]),
    .CO(rcv_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[4]),
    .I0(rcv_bitcount[3]),
    .I1(1'h1)
  );
  /* src = "MappedSPIFlash_V3.v:117.31-117.50|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY rcv_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3_SB_CARRY_CO_2 (
    .CI(rcv_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[2]),
    .CO(rcv_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[3]),
    .I0(rcv_bitcount[2]),
    .I1(1'h1)
  );
  /* src = "MappedSPIFlash_V3.v:117.31-117.50|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY rcv_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3_SB_CARRY_CO_3 (
    .CI(rcv_bitcount[0]),
    .CO(rcv_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[2]),
    .I0(rcv_bitcount[1]),
    .I1(1'h1)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:117.31-117.50|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h8228)
  ) rcv_bitcount_SB_DFFNESR_Q_D_SB_LUT4_O (
    .I0(state[3]),
    .I1(rcv_bitcount[1]),
    .I2(1'h1),
    .I3(rcv_bitcount[0]),
    .O(rcv_bitcount_SB_DFFNESR_Q_D[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:117.31-117.50|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h8228)
  ) rcv_bitcount_SB_DFFNESR_Q_D_SB_LUT4_O_1 (
    .I0(state[3]),
    .I1(rcv_bitcount[4]),
    .I2(1'h1),
    .I3(rcv_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[4]),
    .O(rcv_bitcount_SB_DFFNESR_Q_D[4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:117.31-117.50|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h8228)
  ) rcv_bitcount_SB_DFFNESR_Q_D_SB_LUT4_O_2 (
    .I0(state[3]),
    .I1(rcv_bitcount[3]),
    .I2(1'h1),
    .I3(rcv_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[3]),
    .O(rcv_bitcount_SB_DFFNESR_Q_D[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:117.31-117.50|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h8228)
  ) rcv_bitcount_SB_DFFNESR_Q_D_SB_LUT4_O_3 (
    .I0(state[3]),
    .I1(rcv_bitcount[2]),
    .I2(1'h1),
    .I3(rcv_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[2]),
    .O(rcv_bitcount_SB_DFFNESR_Q_D[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h0f00)
  ) rcv_bitcount_SB_DFFNESR_Q_D_SB_LUT4_O_4 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(rcv_bitcount[0]),
    .I3(state[3]),
    .O(rcv_bitcount_SB_DFFNESR_Q_D[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q (
    .C(clk),
    .D(rcv_data[30]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[31])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_1 (
    .C(clk),
    .D(rcv_data[29]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[30])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_10 (
    .C(clk),
    .D(rcv_data[20]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[21])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_11 (
    .C(clk),
    .D(rcv_data[19]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[20])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_12 (
    .C(clk),
    .D(rcv_data[18]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[19])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_13 (
    .C(clk),
    .D(rcv_data[17]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[18])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_14 (
    .C(clk),
    .D(rcv_data[16]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[17])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_15 (
    .C(clk),
    .D(rcv_data[15]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[16])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_16 (
    .C(clk),
    .D(rcv_data[14]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[15])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_17 (
    .C(clk),
    .D(rcv_data[13]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[14])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_18 (
    .C(clk),
    .D(rcv_data[12]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[13])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_19 (
    .C(clk),
    .D(rcv_data[11]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[12])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_2 (
    .C(clk),
    .D(rcv_data[28]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[29])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_20 (
    .C(clk),
    .D(rcv_data[10]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[11])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_21 (
    .C(clk),
    .D(rcv_data[9]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[10])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_22 (
    .C(clk),
    .D(rcv_data[8]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[9])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_23 (
    .C(clk),
    .D(rcv_data[7]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[8])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_24 (
    .C(clk),
    .D(rcv_data[6]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[7])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_25 (
    .C(clk),
    .D(rcv_data[5]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[6])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_26 (
    .C(clk),
    .D(rcv_data[4]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[5])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_27 (
    .C(clk),
    .D(rcv_data[3]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_28 (
    .C(clk),
    .D(rcv_data[2]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_29 (
    .C(clk),
    .D(rcv_data[1]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_3 (
    .C(clk),
    .D(rcv_data[27]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[28])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_30 (
    .C(clk),
    .D(rcv_data[0]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_31 (
    .C(clk),
    .D(MISO),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_4 (
    .C(clk),
    .D(rcv_data[26]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[27])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_5 (
    .C(clk),
    .D(rcv_data[25]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[26])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_6 (
    .C(clk),
    .D(rcv_data[24]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[25])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_7 (
    .C(clk),
    .D(rcv_data[23]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[24])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_8 (
    .C(clk),
    .D(rcv_data[22]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[23])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:4.57-4.103" */
  SB_DFFNE rcv_data_SB_DFFNE_Q_9 (
    .C(clk),
    .D(rcv_data[21]),
    .E(reset_SB_LUT4_I3_O[3]),
    .Q(rcv_data[22])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h7000)
  ) reset_SB_LUT4_I3 (
    .I0(clk_div_SB_LUT4_I3_1_O[2]),
    .I1(clk_div_SB_LUT4_I3_1_O[1]),
    .I2(clk_div_SB_LUT4_I3_1_O[0]),
    .I3(reset),
    .O(reset_SB_LUT4_I3_O[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf800)
  ) rstrb_SB_LUT4_I0 (
    .I0(rstrb),
    .I1(state[2]),
    .I2(clk_div_SB_LUT4_I0_O[1]),
    .I3(reset),
    .O(state_SB_DFFN_Q_2_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf400)
  ) rstrb_SB_LUT4_I0_1 (
    .I0(rstrb),
    .I1(state[2]),
    .I2(state[0]),
    .I3(reset),
    .O(state_SB_DFFN_Q_1_D)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:22.34-23.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf300)
  ) rstrb_SB_LUT4_I2 (
    .I0(1'h0),
    .I1(state[2]),
    .I2(rstrb),
    .I3(reset),
    .O(rstrb_SB_LUT4_I2_O[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h0100)
  ) rstrb_SB_LUT4_I2_O_SB_LUT4_I3 (
    .I0(clk_div_SB_LUT4_I3_O[0]),
    .I1(clk_div_SB_LUT4_I3_O[1]),
    .I2(clk_div_SB_LUT4_I3_O[2]),
    .I3(rstrb_SB_LUT4_I2_O[2]),
    .O(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_O)
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h0100)
  ) rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1 (
    .I0(clk_div_SB_LUT4_I3_O[0]),
    .I1(snd_bitcount_SB_DFFNESR_Q_R[1]),
    .I2(clk_div_SB_LUT4_I3_O[1]),
    .I3(rstrb_SB_LUT4_I2_O[2]),
    .O(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_1_O)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR snd_bitcount_SB_DFFNESR_Q (
    .C(clk),
    .D(snd_bitcount_SB_DFFNESR_Q_D[0]),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_O),
    .Q(snd_bitcount[0]),
    .R(snd_bitcount_SB_DFFNESR_Q_R[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR snd_bitcount_SB_DFFNESR_Q_1 (
    .C(clk),
    .D(snd_bitcount_SB_DFFNESR_Q_D[1]),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_O),
    .Q(snd_bitcount[1]),
    .R(snd_bitcount_SB_DFFNESR_Q_R[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR snd_bitcount_SB_DFFNESR_Q_2 (
    .C(clk),
    .D(snd_bitcount_SB_DFFNESR_Q_D[2]),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_O),
    .Q(snd_bitcount[2]),
    .R(snd_bitcount_SB_DFFNESR_Q_R[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR snd_bitcount_SB_DFFNESR_Q_3 (
    .C(clk),
    .D(snd_bitcount_SB_DFFNESR_Q_D[3]),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_O),
    .Q(snd_bitcount[3]),
    .R(snd_bitcount_SB_DFFNESR_Q_R[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR snd_bitcount_SB_DFFNESR_Q_4 (
    .C(clk),
    .D(snd_bitcount_SB_DFFNESR_Q_D[4]),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_O),
    .Q(snd_bitcount[4]),
    .R(snd_bitcount_SB_DFFNESR_Q_R[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:67.1-129.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:22.66-22.119" */
  SB_DFFNESR snd_bitcount_SB_DFFNESR_Q_5 (
    .C(clk),
    .D(snd_bitcount_SB_DFFNESR_Q_5_D[5]),
    .E(rstrb_SB_LUT4_I2_O_SB_LUT4_I3_O),
    .Q(snd_bitcount[5]),
    .R(snd_bitcount_SB_DFFNESR_Q_R[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:102.29-102.48|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hf8f2)
  ) snd_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O (
    .I0(state[1]),
    .I1(snd_bitcount[5]),
    .I2(state[2]),
    .I3(snd_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[5]),
    .O(snd_bitcount_SB_DFFNESR_Q_5_D[5])
  );
  /* src = "MappedSPIFlash_V3.v:102.29-102.48|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY snd_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3_SB_CARRY_CO (
    .CI(snd_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[4]),
    .CO(snd_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[5]),
    .I0(snd_bitcount[4]),
    .I1(1'h1)
  );
  /* src = "MappedSPIFlash_V3.v:102.29-102.48|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY snd_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3_SB_CARRY_CO_1 (
    .CI(snd_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[3]),
    .CO(snd_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[4]),
    .I0(snd_bitcount[3]),
    .I1(1'h1)
  );
  /* src = "MappedSPIFlash_V3.v:102.29-102.48|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY snd_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3_SB_CARRY_CO_2 (
    .CI(snd_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[2]),
    .CO(snd_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[3]),
    .I0(snd_bitcount[2]),
    .I1(1'h1)
  );
  /* src = "MappedSPIFlash_V3.v:102.29-102.48|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4" */
  SB_CARRY snd_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3_SB_CARRY_CO_3 (
    .CI(snd_bitcount[0]),
    .CO(snd_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[2]),
    .I0(snd_bitcount[1]),
    .I1(1'h1)
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:102.29-102.48|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h8228)
  ) snd_bitcount_SB_DFFNESR_Q_D_SB_LUT4_O (
    .I0(state[1]),
    .I1(snd_bitcount[4]),
    .I2(1'h1),
    .I3(snd_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[4]),
    .O(snd_bitcount_SB_DFFNESR_Q_D[4])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:102.29-102.48|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h8228)
  ) snd_bitcount_SB_DFFNESR_Q_D_SB_LUT4_O_1 (
    .I0(state[1]),
    .I1(snd_bitcount[3]),
    .I2(1'h1),
    .I3(snd_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[3]),
    .O(snd_bitcount_SB_DFFNESR_Q_D[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:102.29-102.48|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h8228)
  ) snd_bitcount_SB_DFFNESR_Q_D_SB_LUT4_O_2 (
    .I0(state[1]),
    .I1(snd_bitcount[2]),
    .I2(1'h1),
    .I3(snd_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[2]),
    .O(snd_bitcount_SB_DFFNESR_Q_D[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "MappedSPIFlash_V3.v:102.29-102.48|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/arith_map.v:62.5-70.4|/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h8228)
  ) snd_bitcount_SB_DFFNESR_Q_D_SB_LUT4_O_3 (
    .I0(state[1]),
    .I1(snd_bitcount[1]),
    .I2(1'h1),
    .I3(snd_bitcount[0]),
    .O(snd_bitcount_SB_DFFNESR_Q_D[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h0f00)
  ) snd_bitcount_SB_DFFNESR_Q_D_SB_LUT4_O_4 (
    .I0(1'h0),
    .I1(1'h0),
    .I2(snd_bitcount[0]),
    .I3(state[1]),
    .O(snd_bitcount_SB_DFFNESR_Q_D[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:17.34-18.52" */
  SB_LUT4 #(
    .LUT_INIT(16'h000f)
  ) snd_bitcount_SB_DFFNESR_Q_R_SB_LUT4_O (
    .I0(1'h0),
    .I1(1'h0),
    .I2(state[1]),
    .I3(state[2]),
    .O(snd_bitcount_SB_DFFNESR_Q_R[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:1.51-1.90" */
  SB_DFFN state_SB_DFFN_Q (
    .C(clk),
    .D(state_SB_DFFN_Q_D),
    .Q(state[3])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:1.51-1.90" */
  SB_DFFN state_SB_DFFN_Q_1 (
    .C(clk),
    .D(state_SB_DFFN_Q_1_D),
    .Q(state[2])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:1.51-1.90" */
  SB_DFFN state_SB_DFFN_Q_2 (
    .C(clk),
    .D(state_SB_DFFN_Q_2_D),
    .Q(state[1])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/ff_map.v:1.51-1.90" */
  SB_DFFN state_SB_DFFN_Q_3 (
    .C(clk),
    .D(clk_div_SB_LUT4_I0_O[0]),
    .Q(state[0])
  );
  /* module_not_derived = 32'd1 */
  /* src = "/home/carlos/miniconda3/envs/fpga/bin/../share/yosys/ice40/cells_map.v:26.33-27.52" */
  SB_LUT4 #(
    .LUT_INIT(16'hffe0)
  ) state_SB_DFFN_Q_D_SB_LUT4_O (
    .I0(clk_div_SB_LUT4_I3_O[0]),
    .I1(clk_div_SB_LUT4_I2_O[2]),
    .I2(reset),
    .I3(reset_SB_LUT4_I3_O[3]),
    .O(state_SB_DFFN_Q_D)
  );
  assign clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_LUT4_I3_O[0] = CLK_SB_DFFNESR_Q_E_SB_LUT4_O_I1[1];
  assign clk_div_SB_LUT4_I2_O[0] = state[0];
  assign CLK_SB_DFFNESR_Q_E_SB_LUT4_O_I1[3:2] = { clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3[5], reset };
  assign clk_div_SB_LUT4_I3_I0[3:2] = { clk_div, state[1] };
  assign reset_SB_LUT4_I3_O[2:0] = { reset, clk_div_SB_LUT4_I2_O[2], clk_div_SB_LUT4_I3_O[0] };
  assign rstrb_SB_LUT4_I2_O[1:0] = { state[2], state[0] };
  assign clk_div_SB_LUT4_I3_O[3] = rstrb_SB_LUT4_I2_O[2];
  assign clk_div_SB_LUT4_I3_1_O[3] = reset;
  assign clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI[1:0] = { div_counter_SB_DFFNSR_Q_5_D[0], 1'h1 };
  assign clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3[4:0] = { clk_div_SB_DFFNSR_Q_D_SB_LUT4_O_I3_SB_CARRY_CO_CI[5:2], div_counter_SB_DFFNSR_Q_5_D[0] };
  assign div_counter_SB_DFFNSR_Q_D_SB_LUT4_O_I3[1:0] = { div_counter[0], 1'h0 };
  assign div_counter_SB_DFFNSR_Q_D[0] = div_counter_SB_DFFNSR_Q_5_D[0];
  assign snd_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[1:0] = { snd_bitcount[0], 1'h1 };
  assign { snd_bitcount_SB_DFFNESR_Q_R[3:2], snd_bitcount_SB_DFFNESR_Q_R[0] } = { rstrb_SB_LUT4_I2_O[2], clk_div_SB_LUT4_I3_O[1:0] };
  assign rcv_bitcount_SB_DFFNESR_Q_5_D_SB_LUT4_O_I3[1:0] = { rcv_bitcount[0], 1'h1 };
  assign rcv_bitcount_SB_DFFNESR_Q_D[11:6] = { state[1], 5'h00 };
  assign rcv_bitcount_SB_DFFNESR_Q_5_D[4:0] = rcv_bitcount_SB_DFFNESR_Q_D[4:0];
  assign snd_bitcount_SB_DFFNESR_Q_D[11:6] = { state[2], 5'h00 };
  assign snd_bitcount_SB_DFFNESR_Q_5_D[4:0] = snd_bitcount_SB_DFFNESR_Q_D[4:0];
  assign cmd_addr[31] = MOSI;
  assign rbusy = 1'h0;
  assign rdata = { rcv_data[7:0], rcv_data[15:8], rcv_data[23:16], rcv_data[31:24] };
endmodule
